# Generated by Django 4.2.4 on 2023-09-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category', verbose_name='Категория')),
            ],
        ),
    ]
