# Generated by Django 4.2.5 on 2023-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
